networks:
  dockercoins:
    internal: true
secrets:
  secret-hasher:
    file: $PWD/hasher/hasher.rb
  secret-rng:
    file: $PWD/rng/rng.py
  secret-webui:
    file: $PWD/webui/webui.js
  secret-worker:
    file: $PWD/worker/worker.py  
services: 
  hasher:
    command:
      -
        hasher.rb
    entrypoint
      -
        rubi
    environment:
      autor: Guillermo
    image: ggacer/ruby:sinatra-thin
    networks:
      -
        dockercoins
    restart: always
    secrets:
      -
        mode: 0400
        source: secret-hasher
        target: /data/hasher.rb
        uid: '65534'
    user: nobody
    working_dir: /data/
  redis:
      command:
        -
          redis-server
      entrypoint
        -
          docker-entrypoint.sh
      environment:
        autor: Guillermo
      image: ggacer/redis:alpine
      networks:
        -
          dockercoins
      restart: always
      volumes:
        -
          read_only: false
          source: volume-redis
          target: /data/
          type: volume
      working_dir: /data/
  webui:
    command:
      -
        webui.js
    entrypoint
      -
        node
    environment:
      autor: Guillermo
    image: ggacer/node:4-slim-express-redis
    networks:
      -
        dockercoins
    ports:
      -
        8080:80
    restart: always
    secrets:
      -
        mode: 0400
        source: secret-webui
        target: /data/webui.js
        uid: '65534'
    user: nobody
    working_dir: /data/
  rng:
    command:
      -
        rng.py
    entrypoint
      -
        python
    environment:
      autor: Guillermo
    image: ggacer/python:flask
    networks:
      -
        dockercoins
    restart: always
    secrets:
      -
        mode: 0400
        source: secret-rng
        target: /data/rng.py
        uid: '65534'
    user: nobody
    working_dir: /data/
  worker:
    command:
      -
        worker.rb
    entrypoint
      -
        python
    environment:
      autor: Guillermo
    image: python:redis-requests
    networks:
      -
        dockercoins
    restart: always
    secrets:
      -
        mode: 0400
        source: secret-worker
        target: /data/worker.py
        uid: '65534'
    user: nobody
    working_dir: /data/
version: '3.9' 
volumes:
  volume-redis:
  
